### ISSUE TITLE
Design New Reports UI

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#1525]
## User Story

As an `admin` I want my reports to be `flexible` and `comprehensive` so that I can get a `full picture of my donations` yet am able to `drill down to more granular reports` so I can completely understand my donors and donations.

## Acceptance Criteria

- [x] I can filter reports by date, donation form, and receive informative and actionable data.

**Comment by mehul0810** [comment]
While working on PR https://github.com/WordImpress/Give/pull/2529, changing filter to `This Quarter/Month` or `Last Quarter/Month`, I've noticed that income reports shows donation on 1st of each month irrespective of the donation performed on the day of the quarter or month.

For Example, if the donation performed on 13th July 2017. But, It shows on 1st July 2017 in the income reports.

I and @ravinderk had a discussion over call and concluded that we can include it when we revamp the Reports UI as the issue is of low priority. 

## Screenshot
![image](https://user-images.githubusercontent.com/1852711/34027061-49ccf5c6-e180-11e7-940e-9deb80b68a04.png)

## Issues to cross-check and fix while revamping Reports UI
1. https://github.com/WordImpress/Give/issues/2530
2. Above mentioned incorrect day shown in Income Reports when we filter with larger span.

**Comment by DevinWalker** [comment]
The design for the reports has been completed for the initial release and we have more ready for future iterations.
