### ISSUE TITLE
epic: GiveWP Campaign Builder

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#2905]
## User Story

As a Give user, I want more control over all aspects of form creation and display so that I can design the user experience that works best for my donors.

## Current Behavior

I currently am limited by the options available in the form creation process, especially when it comes to determining the order of form elements or designing multi-stepped forms.

## Expected Behavior

I expect to determine the exact fields and order in which those fields display. I would also like to match the look and feel of multi-step donation forms that I might have seen elsewhere on the web.

## Possible Solution

A config-based approach to form creation will solve many problems associated with the current hook-based approach. While a config-based approach will obviously benefit developers, we can also layer a UI on top of the Form API for users to create powerful forms without code.

### Issues
- feat(form): identify form-building concerns and possible Fields API #1038
- feat(form): identify areas of improvement for existing forms #1457
- feat(form): allow form configs to be imported and exported #2012

### Resources

- https://github.com/mozilla-services/react-jsonschema-form
- https://github.com/oomphinc/WP-Forms-API
- https://wordpress.stackexchange.com/questions/48343/does-wordpress-have-a-form-api/48367#48367

**Comment by mathetos** [comment]
Just adding a note here for future reference. As we build out the new markup for our fields, I looked into doing some CSS styling of labels and inputs, and it seems we have FAR more flexibility with CSS if we put the `label` AFTER the `input` instead of before as we do currently. 

See some examples here:
https://tympanus.net/Development/TextInputEffects/index2.html

Essentially, to do some CSS styling with the label based on the focus of the input, the only way to do that with CSS is as so:
`input:focus + label {do stuff here}`

But our current markup is:
`label + input` 

Naturally this isn't the only concern, but I'm thinking we might not need the float.js library at all if we change the markup a bit.

**Comment by mathetos** [comment]
Another note:
We most likely don't want to use placeholder text in our inputs anymore either as long as our labels are done correctly and fully accessible. 

https://www.smashingmagazine.com/2018/06/placeholder-attribute/

**Comment by DevinWalker** [comment]
Closing epic as too broad and out of date now.
