### ISSUE TITLE
epic: add Square to core with application fee

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4292]
As a user I want to use Square payment gateway without having to purchase the Square addon and be charged a percentage for one-time donations instead.

**Comment by mehul0810** [comment]
@mikejhale @DevinWalker 

I've explained overall understanding of what I did with Square and what is pending in the video.

**Video Link:** https://www.loom.com/share/21f0acb646474060923b48e2e4a27d0b

Let me know if you have any questions

**Comment by DevinWalker** [comment]
Square's API has a long way to go (support subscriptions) before we go this route. Until then, I think it's best to keep developing and supporting it as a premium gateway offering. I have a few meetings with Square coming up to see how our integration is working with them so far so that will help inform things here. Closing until we get more serious about it and it makes business sense.
