### ISSUE TITLE
fix(licensing): resolve "too many redirects" error for recurring Donations updates

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4304]
# Bug Report

## User Story

I want to update my add-ons with no issue.

## Current Behavior
On the Recurring donations add-on, I am getting the error `too many redirects` when trying to autoupdate through the plugins page.

## Expected Behavior
I expect it to update, or for the error to be more helpful.

## Bug Type
- [x] This bug describes functionality that once worked as expected in some previous version.

## Steps to Reproduce

1. Install recurring Donations version 1.9.4 or 1.9.5 on a test site.
2. Activate the license key on the licenses tab
3. Go to the plugins page and attempt to update. 

## Possible Solution
I have credentials to a test site where it is occurring currently. 

## Related
https://secure.helpscout.net/conversation/1006564975/50785
https://secure.helpscout.net/conversation/1005503965/50697
https://secure.helpscout.net/conversation/1008788026/50921
https://secure.helpscout.net/conversation/1009524253/50949

## Acceptance Criteria
- [ ] I'm able to update with no issue.
- [ ] if the problem extends to other add-ons, it is resolved there as well.

**Comment by DevinWalker** [comment]
@Benunc this has been resolved. As predicted, the issue was with the website and this setting being reset somehow:

![2019-11-20_17-28-57](https://user-images.githubusercontent.com/1571635/69292563-4dc88c00-0bbb-11ea-9142-fdc633f18549.png)

I went in and updated it to select the proper file and now updates are working as expected:

![2019-11-20_17-28-18](https://user-images.githubusercontent.com/1571635/69292586-5faa2f00-0bbb-11ea-9747-e3e1344b0f80.png)

There's an open issue to validated EDD fields when updating the downloads post type to resolve issues like this happening: https://github.com/impress-org/givewp-website/issues/329

We've seen this occur before when the `readme.txt` field empties or other fields. I haven't isolated how exactly this happens because it doesn't seem to be reliably reproducible. It's very annoying though and often not plain to troubleshoot as I didn't think to look at this field until scanning for the third time today the fields for the Recurring download post. 

It's safe to tell all clients now that they can safely update.
