### ISSUE TITLE
feat: replace  webpack with laravel mix 

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4346]
# Feature Request

## User Story
As a developer, I found that it will take less time to configure laravel mix as compare to webpack because it will take care of a lot of things internally that why you will get a slick file with understandable configuration. We adapted this for other projects and found them useful.

https://laravel-mix.com/

## Acceptance Criteria
- [ ] All configurations are working as expected.

**Comment by henryholtgeerts** [comment]
Following a discussion this morning, this issue is being put on the backburner. The current Webpack config gets the job done and spending too much time on this move to Laravel Mix might cancel out gains offered by an easier to read config file. The associated PR has been closed. The main snag is with correctly copying the images folder. Currantly, Mix is not copying GIFs and is not not copying subdirectories.

**Comment by DevinWalker** [comment]
Closing as lumen was determined to not fit our needs.
