### ISSUE TITLE
Error creating new donation due to new templates

### ISSUE THREAD

**Issue by gaudigva** [impress-org/givewp#4884]
When i try to create a new donation, when saving it, I've got that error : 
An error of type E_ERROR was caused in line 112 of the file /home/cibpynqb/public_html/wp-content/plugins/give/src/Form/Templates.php. Error message: Uncaught Error: Class name must be a valid object or a string in /home/cibpynqb/public_html/wp-content/plugins/give/src/Form/Templates.php:112
Stack trace:
#0 /home/cibpynqb/public_html/wp-content/plugins/give/src/Form/Templates.php(98): Give\Form\Templates->getTemplateObject('')
#1 /home/cibpynqb/public_html/wp-content/plugins/give/src/Helpers/Form/Template.php(50): Give\Form\Templates->getTemplate('')
#2 /home/cibpynqb/public_html/wp-content/plugins/give/includes/admin/forms/class-metabox-form-data.php(1141): Give\Helpers\Form\Template::saveOptions(1039, Array)
#3 /home/cibpynqb/public_html/wp-includes/class-wp-hook.php(289): Give_MetaBox_Form_Data->save_form_template_settings('_give_form_temp...', 'sequoia', 1039)
#4 /home/cibpynqb/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/cibpynqb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /home/cibpynqb/public_html/wp-content/plugins/give/includes/admin/forms/class-metabox-form-data.php(1035): do

best regards ;)

**Comment by DevinWalker** [comment]
Both @ravinderk and myself are unable to reproduce. Please let us know more specifically how to get this PHP notice to appear. Creating a new donation form isn't reproducing it for us.

**Comment by ravinderk** [comment]
@gaudigva Can you confirm that you are not getting any javascript error on `Add Form` page? because we implemented a logic that you can not save existing or new donation form settings until you choose a `Form Template`.

Admin will see this alert when `Form Template` is not selected:
![image](https://user-images.githubusercontent.com/1784821/86268003-2b80fd00-bbe5-11ea-853d-6115326d6c7c.png)

**Comment by gaudigva** [comment]
Hello,
No, i don't have javascript error when i open my form existing form I had before upgrading to v2.7 or when I open the New Donation form.
I've selected Multi-Step Donation Form Template, and when i update it, it's starting to process and a few seconds after, I've got that error : https://mywebsite.com/wp-admin/post.php 500

And it's the same when I'm creating a new form with Multi-Step Template form and also Legacy Donation Form.
And If i don't choose a template, I've got the message telling me to choose one.

I'm using Wordpress 5.4.2 and all my plugins are up to date. And I hadn't that problem with v2.6.3.

**Comment by matheuswd** [comment]
Hi @gaudigva,

We've tested this and we are unable to replicate this issue. I noticed that you are facing an error 500, which makes me think that there is some incompatibility with your other plugins or themes. 

This is also the reason that makes me think it's not an issue with the plugin itself, so you do not need to open a Github issue. In this case, if you have a paid plan, you can contact us via [priority support](https://givewp.com/priority-support/). Otherwise, you can reach out via [WordPress.org for free support.](https://wordpress.org/support/plugin/give/) These are the best places to discuss this kind of issue you are facing.

Send us a message on these channels and we'll get back to with troubleshooting suggestions.

Looking forward to helping you get to the bottom of this!
