### ISSUE TITLE
PayPal Donations webhook notice needs to be actionable and informative

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5287]
## Issue Description

In the case there is an issue with Webhooks we need to provide actionable notices. Currently this notice displays:

![2020-09-22_13-02-33](https://user-images.githubusercontent.com/1571635/93931752-12638600-fcd4-11ea-8c6a-2952fc8f6cae.png)

1. It does not contain a link to the appropriate settings page so I can perform the requested action. As well, we should provide a link to documentation for additional information.
2. Can we also detect if the site is inaccessible by webhooks? For instance, in the case that I'm using the plugin locally for development or testing like I am here.
3. Dismissing the notice doesn't actually dismiss it. On page refresh it appears again so this dismiss button doesn't work.

**Comment by JasonTheAdams** [comment]
@DevinWalker I made a post for this in Canny and linked it. I'm most concerned about the fact that you said it just popped up at one point and won't go away. Do you have any logs that pertain to the issue?

For point 2, it's not quite as critical that we have a check as it is for Stripe. The reason we need it for Stripe is because we're relying on the user to set up the webhook. As such it's important to see if it's working. For PayPal Donations we're setting up the webhooks ourselves, and the PayPal API confirms that it's set up. The fact that you're seeing this message indicates that the API is responding that there's an issue, so you should have something in your Tools > Logs for the failed request.

**Comment by DevinWalker** [comment]
Here's what I see in the logs:

![2020-10-15_13-56-53](https://user-images.githubusercontent.com/1571635/96185150-55d59c80-0eee-11eb-8f7e-356eba196f69.png)

![2020-10-15_13-57-06](https://user-images.githubusercontent.com/1571635/96185159-58d08d00-0eee-11eb-8f3c-daa67e8fc112.png)

**Comment by JasonTheAdams** [comment]
@ravinderk Please look into this.

**Comment by ravinderk** [comment]
@JasonTheAdams I faced this issue multiple times on the localhost and I resolved it by reconnecting. I never face this issue on a live testing site. I think the PayPal access token for the localhost works differently and for every localhost connection PayPal stores access token in cache instead of database + cache. We have to reach to PayPal to confirm my understanding. Let me know what do you think.

**Comment by JasonTheAdams** [comment]
@ravinderk I'm glad to hear your live site has never had the problem. Honestly, I would be a bit surprised if they were doing something special for local sites (they would have to make assumptions based on the TLD), but you're welcome to ask Swati.

**Comment by ravinderk** [comment]
@JasonTheAdams I doubt that this is also happening because we are connecting and disconnecting the same PayPal account continuously on different local sites. This can be a reason for failing access token because the access token always generates fresh of a new connection.

**Comment by JasonTheAdams** [comment]
We addressed the UX issues in this Issue within #5389. The webhooks error shouldn't show up on pages other than the connect screen, and believe a fix is in place for the root of this. As such, I'm closing this Issue. We can open another of further related problem arise.
