### ISSUE TITLE
last time. Complete connection to WooCommerce

### ISSUE THREAD

**Issue by MOSHE1111** [impress-org/givewp#5373]
I see on the net that I'm not the first to think about it.
WooCommerce is something that can be connected to a lot of functions easily, with thousands of plugins of all kinds, like all kinds of affiliate links, vendor links, and a whole lot more. You know I'm not working on you.
It is really not superfluous to define that the payment rate will be through the payment of WooCommerce.
There are hundreds of payment rates in all kinds of countries in the world, it will take very many years to cover all the rates with your Give plugin.
I do not see anything close to each other ever happening.
But WooCommerce does cover a lot of payment rates in all sorts of countries.
In my country I do not think there is any payment rate that is connected to plugin give other than PayPal which is expensive anyway as long as I do not meet their conditions.
Some people in some countries do not use this supplement just because of the issue of exchange rate compatibility. And how much the fix for that depends on only one thing.
Excuse me for my English, because I am stronger in other languages ​​...
When I checked the developer documents, I realized that your plugin works very easily, it records the payment rate, and when the payment rate ends it finishes the recording, and it moves on to payment approval. And the payment is recorded in the campaign.
What needs to be done is a few things.
1. Create a new gateway will be set up for WooCommerce and will contain only personal fields (if skipped at the WooCommerce checkout, see below) with no credit information. For this I have not yet found a solution to remove these fields.
2. Second thing to define is that in the donation button he makes a compulsion to add to the basket at equal to the price of the donation.
I have a lot of ideas to make a code of coercion for adding a payment confirmation, or coercion of adding to a cart by code, and changing a product by dynamic. All of this has a lot of such codes offered, but I have not been able to put together something that will work for me and support the function of a donate button and the amount will be equal to it.
3. A third thing is to define that the recording will apply to this payment and the recording will end upon completion (and registration of the donation report) after confirmation of payment.
4. Fourth thing is to set a reference to the checkout after adding to the cart by product [if using the product ID] and set to remove fields by product. I have a similar code that does similar things.
Alternatively you can set the removal of each basket and cashier page and refer directly to the payment if it is on a separate page, and if it is on the payment page to remove all the fields (leave it ID by account created by typing the previous email or leave one field for emailing the donor ID).
I'm ready to start offering the codes I tried to use, if you're interested in testing them.
Thanks in advance

**Comment by MOSHE1111** [comment]
And with your permission I start the first series of the encoding kit I use:
I have one code whose function is to force an addition to the basket as follows:

`add_action( 'template_redirect', 'quadlayers_add_to_cart_function' );

function quadlayers_add_to_cart_function () {

    $product_id = 1326;

    if ( WC()->cart->get_cart_contents_count() == 0 ) {

        WC()->cart->add_to_cart( $product_id );

    }

}`
And one more code whose job is to change the price dynamically.
`add_filter('woocommerce_get_sale_price', 'my_custom_price', 99);
add_filter('woocommerce_get_price', 'my_custom_price', 99);

function my_custom_price( $orginal_price )
{
    global $post, $woocommerce;

    //your logic for calculating the new price here
    $new_price = $orginal_price / 2;

    //Return the new price (this is the price that will be used everywhere in the store)
    return $new_price;
}`

I would love to know if there is a situation to figure out which action I need to set in your GIVEWP plugin for these actions to take effect after I click the donate button. (By custom rate).

**Comment by MOSHE1111** [comment]
As a continuation of this I would be happy to know if it is possible to configure the code presented here in such a way that it will record the sending for payment in the WooCommerce store and on paying the call he will calculate it with the reports.
https://givewp.com/documentation/developers/how-to-build-a-gateway-add-on-for-givewp/

**Comment by MOSHE1111** [comment]
Now the next thing.
I hope this helps what I am investing here.
There is a code here whose job is to simplify the cash register for some of the products. He removes a coupon, fields, and a shopping cart. Of course it can be controlled and additional fields removed.
https://gist.githubusercontent.com/bekarice/474ab82ab37b8de8617d/raw/fa3aa3eaddd2eb661bfeb288e7a725e896de46ed/wc-free-checkout-fields.php
This code was originally intended for free products. But it may also be used by the ID of a product with a small change.
Personally I would recommend assigning a product to GIVWEWP with a short code, and with this short code set all these codes only on this product.

**Comment by Benunc** [comment]
Hi @MOSHE1111 

It's hard to tell what exactly you are requesting, so I will attempt to restate your ultimate goal here, and then answer as succinctly as possible.

Primary Goal: Support a gateway that is not currently supported in GiveWP

It looks like all of your attempts to get to that goal are being routed through the solution of "Make GiveWP use WooCommerce gateways."

That apparently has the side benefit of allowing GiveWP donations to be listed alongside Woo products, and in their reports, etc.

In response to that, here are three overarching principles:

1. GiveWP has no plans to integrate any deeper into the WooCommerce ecosystem than we already have with the [Donation Upsells add-on](https://givewp.com/addons/donation-upsells-for-woocommerce/), which allows donations to be added to the cart and processed with WooCommerce gateways.
2. If you want to create your own custom Payment Gateway add-on, we have [a tutorial for that}(https://givewp.com/documentation/developers/how-to-build-a-gateway-add-on-for-givewp/).
3. We have no current plans to develop a "cart" system, though we are actively looking at creating a way to donate to multiple funds in one transaction. 

Point 2 here should be noted carefully, since it looks like much of the custom code you've included centers around functionality already supported by our Donation Upsells add-on.

As for including any of the custom code you have demonstrated here, that's not on any roadmap currently. I'll close this issue now.
