### ISSUE TITLE
Stripe fees should be applied when applicable

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#5555]
## User Story

As a paying customer, I want to be sure I'm using Stripe without fees so that I get the full revenue from my donations.

## Details

There is some recurring confusion which customers have in _how_ to remove the 2% stripe fee applied when only using GiveWP core. Presently, the fee is removed if the Give Stripe add-on is installed. This has led to issues wherein customers didn't understand how important it is to install Give Stripe, as perhaps they thought they don't need any of the extra features it offers.

The fact is, there are other ways to determine whether a person using GiveWP core is a paid customer or someone using the free plugin only. The solution is most likely within the account licensing system, wherein a user enters a license key and our system verifies it. Perhaps we could check to see if there any active licenses.

The goal of this issue is to audit how the fee is applied and removed, and determine any ways we can help honest users and remove the fee when safely applicable.

## Acceptance Criteria

-   [x] The 2% Stripe Fee is removed when a premium add-on or bundle license is active
-   [x] The 2% Stripe Fee remains when only GiveWP core is installed and no licenses are active

**Comment by JasonTheAdams** [comment]
@ravinderk Please review this Issue and spike it for an hour. Come back and leave notes here on what you found and if you have a solution in mind. Reach out to myself or @mathetos if you have any questions. Thanks!

**Comment by ravinderk** [comment]
![image](https://user-images.githubusercontent.com/1784821/104482171-9e375000-55ec-11eb-8ee9-c6b87b5725c3.png)

We are adding application fee only for onetime donations and only if Stripe pro add-on is not active.

License validation is promising solution to toggle application fee for honest user. License validation logic decouple add-on state dependancy from application fee logic. We store license information in database which we sync timely with givewp.com. User will be consider as active if they have validation single license for Stripe pro add-on or bundle license (if Stripe pro is part of bundle).

One question is If we select this route then what will happen to existing users who are using Stripe Pro with expired license because application fee does not apply to them but after this application fee will apply to them.

**Comment by JasonTheAdams** [comment]
Great sleuthing, @ravinderk!

With regards to the license checking, it would be an either-or type of solution: _Either_ the Stripe add-on is installed _or_ they have an active license. So if the license expires but they still have Stripe installed, they're good to go.

Does that align with your thinking, @mathetos?

**Comment by mathetos** [comment]
Yes, @JasonTheAdams essentially. 

We might want it to be closer to Either the Stripe add-on is installed (and/or license activated) OR an All Access Pass is activated.

Maybe something like this:

IF {stripe addon is installed (regardless of whether it's activated or not, or its license is activated or not)}
-- ELSEIF {all access pass is activated}
-- REMOVE fees
