### ISSUE TITLE
Donor Profile UI should be polished

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5628]
## User Story

As a donor, I want the donor profile UI to be polished so that I have a consistent, clean donation service experience.

## Details

While functionality for Donor Profiles has been introduced, and styles are largely consistent, some minor polish needs to be added to ensure that the entire donor profile experience is professional and user ready.

## Additional Context

Figma designs: https://www.figma.com/file/BKr2K0XdDyRRoccJbJKRD7/Epic%3A-Donor-Profile?node-id=397%3A1743

## Acceptance Criteria

-   [x] All buttons use accent color
-   [x] All links should use accent color
-   [x] Cancel subscription window copy and styles are clean
-   [x] iframe loaded state is improved
-   [x] Text controls shoud use consistent padding
-   [x] Inner circle of radio controls should be centered
-   [x] Payment method controls should use accent color for focus state
-   [x] Currency Control should use accent color for focus state
-   [x] Users should see notice when attempting to view a donor profile via a WP acct with no associated donor
-   [x] Donation tables should respect "Sequential Numbering" option
-   [x] Save profile button should indicate "saving" state (similar to subscription management)
-   [x] "Enter" key should work to submit login form
-   [x] "Logout" menu item should be positioned at bottom of menu
-   [x] Logout action should require user confirmation
-   [x] Giving Stats should include decimal seperators (correct currency formatting)
-   [x] Pagination should work correctly/consistently
-   [x] "Dashboard" menu item should be highlighted on load
-   [x] Highlighted menu items should have white background
-   [x] Margins/spacing should be made consistent with Figma designs, see video review for more: https://www.loom.com/share/5cc7809395fd45b9827a37d994259aea

**Comment by DevinWalker** [comment]
@henryholtgeerts really good work so far here. I just did an initial review if the Alpha release and here is my initial review: 

https://www.loom.com/share/5cc7809395fd45b9827a37d994259aea

## 2.10.0 Donor Profiles (and other items) Initial Review

- Why is the zip file size in the Alpha 40+MB when the previous last release was 16mb?
- Recaptcha isn’t working for Donor Profiles when I enable it under Settings.
- What happens when you’re logged in and viewing the donor profile and you’re not a donor?
    - When you’re not a donor and attempt to log in to the Donor profile there is no message or notice that appears
- There is not currently a way for the donor to go from the receipt to the new Donor Profile. The donor journey needs to include a way to go from the Donation Receipt (multi-step) or Success Page (legacy) to the new Donor Profile.
- Under “Donation History” the “Processing Fee” is displaying even when Fee Recovery is not enabled. This is misleading and should not display unless Fee Recovery is enabled. If Fee Recovery is enabled and the processing fee covered then this new line item appears as 
- On a fresh install a “p” string is displaying on the “Donation History” shortcode.
- Badges do not have the proper color for the icons and do not display correctly according to my giving history. It does not appear there is the proper logic coded into the badges for displaying correctly.
- Some of the links are not properly displaying the primary color. For instance the “Back to Donation History” link.
- Sequential ordering - By default, the Sequential ordering feature is enabled for fresh install. Currently, the Donation History tab does not respect whether this feature is enabled or disabled and only displays the Post ID.
- Confirmation Messages and Notices: When updating my Donor Profile there is no confirmation message or validation happening. I can update the name and click the button and it works but to the donor there’s no validation of it succeeding or not.
- Log in / Log out:
    - Clicking the “Enter” key when attempting to log in is not working
    - Logout menu item: There should not be a menu items like “Logout” because it’s too easy for the donor to accidentally click it. When viewing the concept the “Signout” link it at the bottom of the menu. It also would be nice if there was a confirmation to log out.
- Dashboard:
    - This is not displaying the correct currency formatting. There is no proper thousands or decimal separators. 
    - The pagination is not working correctly. When I only have 2 donations there’s a pagination but it goes to a blank page and says “4-2” incorrectly.
    - In the left menu when first logged in “Dashboard” is not properly highlighted
        - As well, highlighted menu items need a white background which is not appearing when I click on each tab
    - Padding / Margins: There are multiple issues with spacing in the dashboard and container. Please see my video for details and look at the Figma concept.

---

I'm leaving the above as bullet points rather than checkboxes so we can discuss the above items and see if you have any questions.

**Comment by henryholtgeerts** [comment]
@DevinWalker Thanks for the initial thoughts -- I appreciate your taking time to make the screen recording and bullet list. I'll take some time this morning to open new issues for broader points you raised, and add smaller polish items this issue's acceptance criteria.

**Comment by henryholtgeerts** [comment]
@DevinWalker I've gone ahead and added new acceptance criteria to this issue to handle smaller, specific items mentioned in your initial review. For larger items, I've created a handful of issues to address them specifically:

- https://github.com/impress-org/givewp/issues/5639
- https://github.com/impress-org/givewp/issues/5638
- https://github.com/impress-org/givewp/issues/5637
- https://github.com/impress-org/givewp/issues/5636

**Comment by DevinWalker** [comment]
Thanks for taking the time to do that @henryholtgeerts
