### ISSUE TITLE
is_give_form() function always retun false.

### ISSUE THREAD

**Issue by asifpix** [impress-org/givewp#5801]
If you open "give/includes/template-functions.php" and check line number 490
here is the code
`return is_singular( array( 'give_form' ) );`
but it should be
`return is_singular( array( 'give_forms' ) );`

It will return true.

Best Regards

**Comment by kjohnson** [comment]
@asifpix thanks for the report!

I'd like to gather a little more feedback as to the issue that this is causing. What unexpected behavior did you experience that lead you to investigating the template-functions file?

While it certainly seems like a straightforward fix, I want to be careful that we understand how this affects the codebase at large. Anytime that I see a wrong boolean value I am cautious to understand why it wasn't caught earlier and what code might rely on the incorrect value.

**Comment by asifpix** [comment]
@kjohnson 
I need to check if this is give form or not. If it is return true then I want to echo a text if not hide the text but when I put this function is_give_form() to check if it is form or not? It returns false even in form page. That is why I went to investigate and when I changed "give_form" to "give_forms" it works finally.

Hope It helps.

Best Regards

**Comment by kjohnson** [comment]
@asifpix thanks for the background info - that is really helpful.

For an immediate resolution, I would suggest using `is_singular( array( 'give_forms' ) )` directly in your code while we investigate and work towards releasing a patch.

**Comment by kjohnson** [comment]
The `is_give_form()` conditional function was introduced back in 2016, at which time it used the singular `give_form`, see https://github.com/impress-org/givewp/pull/831. The implementation has not been modified since that time.

Further, I see no use of the `is_give_form()` function within GiveWP, the core plugin, which seems odd. Further, a GitHub Organization Search for Impress does not show any uses of the function in any add-ons, see https://github.com/search?q=org%3Aimpress-org+is_give_form&type=code

Instead, I see inline comparisons to the post type, for example: https://github.com/impress-org/givewp/blob/775c659589fe106d06b20b9a5fa12a2b19ca9770/includes/admin/forms/dashboard-columns.php#L70

Lastly, the post type slug has always been `give_forms` (plural), as originally set  in [Initial OOP classes build out largely forked from EDD ](https://github.com/impress-org/givewp/blame/775c659589fe106d06b20b9a5fa12a2b19ca9770/includes/post-types.php#L108)

@DevinWalker this leads me to believe that this function has always been broken and thus never used. Therefor it is safe to change.

**Comment by kjohnson** [comment]
@asifpix would you like to submit a Pull Request for the contribution of the bug fix?

**Comment by asifpix** [comment]
@kjohnson sure. Happy to contribute.

**Comment by asifpix** [comment]
Pull request sent. Thanks to all the team members of GiveWP.

Stay safe and best regards
Asif
