### ISSUE TITLE
Field api should support all field input types

### ISSUE THREAD

**Issue by jonwaldstein** [impress-org/givewp#5844]
## User Story

As a developer, I want the field api to support all input types so that I can use it to build custom fields.

## Details

The field api only supports a few input types.  In order to implement the api into our add-on plugins like form field manager, it needs to support all the available input types we offer & their attributes.

## Additional Context

Here's a screenshot of our current input templates.

![Screen Shot 2021-05-26 at 9 16 10 AM](https://user-images.githubusercontent.com/10138447/119666081-056ad980-be03-11eb-828d-49a2537b8d81.png)

## Acceptance Criteria

_All Field Types are supported with proper attributes_

- [x] text
- [x] hidden
- [x] textarea
- [x] select [dropdown]
- [x] select [multi select]
- [x] radio
- [x] checkbox
- [x] file_upload
- [x] url
- [x] email
- [x] repeat
- [x] date
- [x] phone

**Comment by knowler** [comment]
I’m going to go through each field and list what the front-end needs are that need to be ported over in this thread.

**Comment by knowler** [comment]
The Date field:

- The jQuery UI Datepicker that’s included in WordPress. Will need to enqueue this on this side.
- A Timepicker addon.
- We have vendored CSS that we are including.

**Comment by jonwaldstein** [comment]
We're going to need some way of concatenating css classnames to the field types as it seems to be a common option in field manager.

**Comment by knowler** [comment]
Thinking out loud about what we name field types in the Field API:

If we make types like `select`, `radio`, `checkbox`, etc. we are binding ourselves to those HTML elements and I’m not sure that’s what we want, since depending on the needs of a field, there would be multiple appropriate choices for UI. For example, consider the following:

I want a field that lets a user choose out of a number of preset choices. Both an HTML `select` and `input[type=radio]` are appropriate and the difference becomes the preference in UI. Now, say we want to allow multiple choices. In that case, an `input[type=radio]` becomes inappropriate since it does not support the kind of functionality. An `input[type=checkbox]` within a group does become appropriate, since it does support multiple choices to be selected. `select` supports multiple choice so it remains appropriate. One could say that there would be difference between a `select[multiple]` and a `input[type=checkbox]` group since the latter would need unique `name` attributes, but in my opinion that's an implementation detail for the consumer.

I guess what I’m trying to get at here is that it seems to be impossible to get away from the HTML, since we do want the user to be able to choose what UI they want to provide for editing the form. There is a spectrum between having a bunch of data with no opinions with what the UI should be like other than constraints for editing the data and an overly involved API that allows fine-tuning down to the most unnecessary detail. I think we need to find where on the spectrum we sit and commit to it (not that we haven’t — I think it’s been a bit unclear though since the Fields API isn’t in broad use yet).

**Comment by jonwaldstein** [comment]
@knowler i think its okay to bind ourselves to what an html element is because that's what they are going to be rendered by the consumer as.  The input type should be named as the closest thing to what it will represent.  There's only so many inputs you can have in a form and each consumers should be able to register those different types and render them how they see fit.  Internally we can probably re-use different concepts of options in a select, multi-select, radio, checkbox, etc.

Check out how CarbonFields names their input types for creating fields https://docs.carbonfields.net/learn/fields/text.html & if you dig into their Repo you might draw some inspiration on how they share some concepts internally for different type of "option" fields.

**Comment by kjohnson** [comment]
Jason and I have discussed the balance between representing the DOM and maintaining an abstraction. I think it is safe to assume that the DOM will be involved, but we also want to maintain an abstraction for Developer Experience.

**Comment by kjohnson** [comment]
@jonwaldstein @knowler also, the Fields API currently maintains an abstraction for "options", which supports multiple field type, see `src/Framework/FieldsAPI/FormField/FieldOptions.php`.

**Comment by kjohnson** [comment]
@knowler when adding new input types, you probably just need to update the `templates/` in the `LegacyConsumer`. The fields API itself is actually agnostic of field types, but rather structures the properties (with type being an arbitrary string property).
