### ISSUE TITLE
GiveWP should use get_options()

### ISSUE THREAD

**Issue by sebastienserre** [impress-org/givewp#6134]
## User Story
Hello,
I'm Sébastien from the Polylang Pro helpdesk team.
We today had a common customer which had problems to translate option from your GiveWP Tributes add-on.

At https://github.com/impress-org/givewp/blob/0b020fee3aebf1c9cdfc3adb36c334c0cc206ef3/includes/class-give-cache-setting.php#L175
Why don't you use native WordPress `get_option()` functions ?
It could help the ecosystem to interact with your plugins if you use WordPress functions as it will honor filters.

Regards

**Comment by JasonTheAdams** [comment]
Hi @sebastienserre!

Honestly, this is a legacy part of the codebase and not how we'd recommend things to work at this point. This is the first issue we've had reported with this part of codebase. If you're willing to submit a PR that would move this along much more quickly, otherwise I'm not sure when we'll be able to get to refactoring this part of the legacy code.
