### ISSUE TITLE
Data Transfer Object looks for undefined index

### ISSUE THREAD

**Issue by zystvan** [impress-org/givewp#6528]
## Details

When a donation is made through a form with the "Custom Amount" donation option disabled and using the Stripe payment gateway, these two errors appear in the WordPress debug.log: 

```
PHP Notice:  Undefined index: give-form-minimum in /path/to/wordpress/wp-content/plugins/give/src/PaymentGateways/DataTransferObjects/FormData.php on line 128
PHP Notice:  Undefined index: give-form-maximum in /path/to/wordpress/wp-content/plugins/give/src/PaymentGateways/DataTransferObjects/FormData.php on line 129
```

I suspect this happens with other payment gateways as well, but haven't been able to test. 

## Expected Behavior

Donations should be processed without any PHP errors/notices. 

## Steps to Reproduce

1. Enable the WordPress debug.log
2. Configure a donation form to use the Stripe payment gateway and disable the "Custom Amount" donation option
3. Make a donation through the form
4. See the two PHP notices in the debug.log

## System Information

<details><summary>Details</summary>

```
### WordPress Environment ###

Home URL: [x]
Site URL: [x]
WP Version: 6.0.1
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: [x]
Page for Posts: Unset
Table Prefix Length: [x]
Table Prefix Length: [x]
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: [x]
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 16 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
PHP Max Upload Size: 16 MB
cURL Version: 7.68.0, OpenSSL/1.1.1f
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.21.4
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp_give_donors✔ wp_give_donormeta✔ wp_give_comments✔ wp_give_commentmeta✔ wp_give_sessions✔ wp_give_formmeta✔ wp_give_sequential_ordering✔ wp_give_donationmeta✔ wp_give_revenue✔ wp_give_migrations✔ wp_give_log
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email❌Admin Renewal Receipt Email❌Subscription Cancelled Email❌Admin Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.21.1
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: [x]
Failure Page: [x]
Donation History Page: [x]
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Authorize.net, PayPal Standard
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Notifications: IPN Received [x] Status VERIFIED
Donor Email Access: Enabled
Stripe Webhook Notifications: August 10, 2022 [x]

### Active GiveWP Add-ons ###

[x]
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.4.1
[x]

### Other Active Plugins ###

[x]

### Inactive Plugins ###

[x]

### Active MU Plugins ###

[x]

### Theme ###

[x]
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
```

</details>

## Acceptance Criteria

Something happens when an action is taken.

## Possible Fixes

- Add the `give-form-minimum` and `give-form-maximum` fields to all forms, whether custom amounts are allowed or not. 
- Check if the index exists before using it. 

I can submit a PR to fix this bug if one of those would be an acceptable fix.

**Comment by JoshuaHungDinh** [comment]
Dear @zystvan,

I wanted to follow up on this issue. We had encountered a backlog of submitted issues, which made it challenging to manage all of the developer submissions. As a result, occasional submissions like this one may not have gotten the attention they deserve. We do appreciate the effort you put into providing us with a detailed report.

In order to improve our efficiency in promptly addressing issues, we are implementing a strategy to maintain our issues list with a primary focus on active items that are currently being addressed.

I have confirmed that the notice you mentioned still persists in the latest version of GiveWP.  For the time being I will be closing this issue. To ensure proper tracking of this specific issue, I have filed a bug report with your details. Including it in our feedback loop in this manner will allow others to vote on the issue and have it properly prioritized for a developer to fix. I would also like to invite you to submit a PR for one of your proposed solutions as it may be the quickest way to a resolution. 

Thank you for helping us improve GiveWP.
