### ISSUE TITLE
Update give_total by Ajax 

### ISSUE THREAD

**Issue by sofiquldev** [impress-org/givewp#6619]
## User Story
When a user pays something, wp show me a receipt. After closing the GiveWP donate form, update the value of give_total from everywhere without reloading the site.

This feature will be helpful for the user.

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by JoshuaHungDinh** [comment]
Hi  @sofiquldev, Id like to have our team prioritize this feature. We ask that you please submit a feature request at https://givewp.canny.io/feature-requests so that other users can vote on it. Doing this will help place your item higher on our list of items to complete.  I’d also like to invite you to submit a PR if you feel necessary as it may be the quickest route to implementation.
