### ISSUE TITLE
Peer2Peer should have Mailchimp (and other providers) integration at registration, not just donation

### ISSUE THREAD

**Issue by slewisma** [impress-org/givewp#6750]
## User Story

As a manager of peer2peer campaigns, I need to be able to email team leaders and fundraisers before they become donors. The registration form should support the same email marketing system integrations as donation forms.

## Details

If a peer2peer campaign has an initial donation requirement such as an entry fee for a 5K, it needs to be easy to send marketing messages to team leaders and fundraisers to remind them to make their initial donation and to send them tips on fundraising. Right now we don't get a chance to get them into a mailing list until they submit a donation form.

## Acceptance Criteria

Anyone that registers as a team leader or fundraiser is added to a mailing list in the email marketing system that is integrated with GiveWP. A specified tag is added to their contact when they are added or updated in the mailing list. Opt-in/opt-out support should be available but the campaign manager should also have the ability to require opt-in as a condition of registration (with appropriate disclosure).

**Comment by kjohnson** [comment]
Hey @slewisma - I'm moving this to our [Feature Request](https://feedback.givewp.com/feature-requests) board, which we use to track incoming requests and aggregate feedback. This will allow the right people to see the request (since GitHub is mostly just the individual developers).

I added the feedback under your name (hopefully I selected the right one) so you should be notified when there is activity on this feature request.

https://feedback.givewp.com/feature-requests/p/peer-to-peer-should-have-mailchimp-and-other-providers-integration-at-registrati
