### ISSUE TITLE
Field node should contain all necessary traits

### ISSUE THREAD

**Issue by jonwaldstein** [impress-org/givewp#6829]
## Details

Every field that extends the main Field node class, is constructing itself with traits.  Some of those make sense for individual fields like `HasMaxLength` but others should be given to all fields like we did with `ShowInAdmin`, `ShowInReceipt`m `StoreAsMeta`.

One recently reported missing: `HasEmailTag` which is being used on all fields in the legacy consumer.  This is problematic if one field is not using that trait as it will cause a fatal error.

So we need to consolidate all the traits that should be applied to _every_ field.

## Additional Context

Related: https://github.com/impress-org/givewp/issues/6828

## Acceptance Criteria

-   [ ] All common field traits are applied to the main Field node class.

**Comment by kjohnson** [comment]
We should consider updating the Fields API to enforce a `Field` interface instead of enforcing the use of the `Field` base class.

For example, the Password field is an exception in that it should not be allowed to be shown in the admin. Extending from the `Field` base class requires that we override every method of the `ShowInAdmin` to prevent the value from being shown. The same goes for field storage.

If we enforced a `Field` interface then we could simply stub the `shouldShowInAdmin` method to return `false`.
